[workspace]
members = [".", "bench"]

[package]
description = "A hex encoding library"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "hector"
version = "0.1.0"

[features]
alloc = []
default = ["std"]
std = ["alloc"]

[dependencies]
