[package]
edition = "2021"
name = "hector"
version = "0.1.0"

[features]
alloc = []
default = ["std"]
std = ["alloc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
